 name: Release
 
 on:
   push:
     tags: 
       - 'v*.*.*'

 jobs:
   release:
     name: build and release Electron app
     runs-on: ${{ matrix.os }}
 
     strategy:
       fail-fast: false
       matrix:
         os: [windows-latest]
 
     steps:
       - name: Check out git repository
         uses: actions/checkout@v3.0.0
 
       - name: Install Node.js
         uses: actions/setup-node@v2
         with:
           node-version: '14.x'
 
       - name: Release for Windows
         if: matrix.os == 'windows-latest'
         run: yarn && yarn build
         env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
